CREATE TABLE IF NOT EXISTS up_cake_tag
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,

	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS up_cake_recipe
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(510),
	TIME INT,
	REACTION INT,
	USER_ID INT,
	DATE_ADDED DATETIME NOT NULL,
	DATE_UPDATED DATETIME,
	PRIMARY KEY(ID),
	FOREIGN KEY FK_CAKE_USER(USER_ID)
		REFERENCES b_user(ID)
		ON UPDATE RESTRICT
		ON DELETE CASCADE
);